model: 
  name: vae.Autoencoder
  encoder:
    hidden_sizes: [128, 64, 12, 3]
  decoder:
    hidden_sizes: [12, 64, 128]
dataset:
  name: vision.MNIST
batch_size: 128
num_epochs: 100
optimizer:
  name: adam
  lr: 0.01
  weight_decay: 1e-5
metrics:
  - mse
output_format: img
