model:
  name: dlex.torch.models.attention.Attention
  encoder:
    rnn_type: lstm
    bidirectional: true
    num_layers: 1
    hidden_size: 128
    output_size: 128
  decoder:
    rnn_type: lstm
    use_attention: true
    num_layers: 1
    hidden_size: 128
    max_length: 50
  attention:
    hidden_size: 256
  decoding_method: beam_search
  beam_search:
    beam_size: 4
    penalty: 1.0
  dropout: 0.0
  teacher_forcing_ratio: 1.0
dataset:
  alias: dummy
  vocab:
    sos_eos: true
    blank: false
  output_format: null
batch_size: 10
num_epochs: 100
optimizer:
  name: adam
  lr: 0.01
metrics:
  - wer
max_grad_norm: 5.0