model:
  name: src.models.rnn_crf.Model
  embed_size: 300
  rnn_type: 'lstm'
  bidirectional: true
  hidden_size: 1000
  dropout: 0.5
  num_layers: 2
dataset:
  name: src.datasets.vnpos.VNPos
  embed_unit: 'word'
  tag_type: pos
  output_format: word+tag
loss: output_mean
batch_size: 128
test_batch_size: 128
num_epochs: 30
optimizer:
  name: adam
  lr: 0.01
metrics:
  - ser
