model:
  name: dlex.torch.models.attention.classifier.LabelSequenceClassifier
  encoder:
    rnn_type: lstm
    bidirectional: false
    num_layers: 2
    input_size: 256
    hidden_size: 512
    output_size: 256
  decoder:
    hidden_size: 256
    output_size: 256
  attention:
    type: bahdanau
    size: 256
  dropout: 0.2
dataset:
  name: dlex.datasets.nlp.imdb.IMDB
  embedding_dim: 300
  pretrained_embeddings: glove
train:
  batch_size: 64
  num_epochs: 50
  optimizer:
    name: adam
    lr: 0.01
test:
  batch_size: 32
  metrics: [acc]