model:
  name: src.models.cnn.BasicModel
dataset:
  name: dlex.datasets.vision.MNIST
  output_format: default
loss: nll_loss.NLLLoss
batch_size: 256
num_epochs: 30
metrics:
  - acc
optimizer:
  name: adam
  lr: 0.001
max_grad_norm: 1.0