model:
  name: src.models.cnn.BasicModel
dataset:
  name: dlex.datasets.image.mnist.MNIST
  output_format: default
train:
  eval: [valid, test]
  batch_size: 256
  num_epochs: 30
  optimizer:
    name: adam
    lr: 0.001
  max_grad_norm: 1.0
test:
  metrics: [acc]