backend: pytorch
env:
  main:
    variables:
      dataset:
        - dlex.datasets.image.mnist.MNIST
        - dlex.datasets.image.cifar.CIFAR10
      test:
        - nothing
model:
  name: src.models.cnn.SimpleModel
dataset:
  name: ~dataset
  output_format: default
train:
  eval: [dev, test]
  batch_size: 256
  num_epochs: 30
  optimizer:
    name: adam
    lr: 0.001
  max_grad_norm: 1.0
test:
  metrics: [err]
