model:
  name: dlex.models.attention.NMT
  encoder:
    rnn_type: lstm
    bidirectional: false
    num_layers: 2
    input_size: 256
    hidden_size: 256
    output_size: 256
    embedding: none
    update_embedding: true
  decoder:
    rnn_type: lstm
    use_attention: true
    num_layers: 1
    hidden_size: 256
    output_size: 256
    max_length: 20
  beam_search:
    beam_size: 8
    max_len_ratio: 0
  attention:
    type: bahdanau
    size: 256
  dropout: 0.1
  teacher_forcing_ratio: 0.5
  decoding_method: beam_search
dataset:
  name: src.datasets.tatoeba.Tatoeba
  source: spa
  target: eng
  output_format: text
batch_size: 16
num_epochs: 50
optimizer:
  name: adam
  lr: 0.001
max_length: 10
metrics:
  - bleu
max_grad_norm: 5.0
