backend: pytorch
model:
  name: dlex.torch.models.transformer.NMT
  num_heads: 8
  key_size: 64
  value_size: 64
  dim_model: 256
  dim_inner: 1024
  encoder:
    rnn_type: lstm
    bidirectional: false
    num_layers: 3
    input_size: 256
    hidden_size: 256
    output_size: 256
    embedding: none
    update_embedding: true
    max_length: 50
  decoder:
    share_embeddings: true
    use_attention: true
    num_layers: 3
    hidden_size: 256
    max_length: 50
    output_size: 256
  beam_search:
    beam_size: 16
    penalty: 0
  attention:
    type: bahdanau
    size: 256
  dropout: 0.01
  teacher_forcing_ratio: 1.0
  decoding_method: greedy
dataset:
  name: src.datasets.wmt16.WMT16
  source: vi
  target: en
  output_format: text
  debug_size: 20
  unit: word
  max_target_length: 50
  max_source_length: 50
  special_tokens: [sos, eos, oov, pad]
train:
  batch_size: 64
  num_epochs: 100
  optimizer:
    name: adam
    lr: 0.01
  max_grad_norm: 1.0
test:
  metrics: [bleu]
