model:
  name: dlex.torch.models.attention.NMT
  encoder:
    rnn_type: lstm
    bidirectional: true
    num_layers: 2
    input_size: 256
    hidden_size: 256
    output_size: 256
  decoder:
    rnn_type: lstm
    use_attention: true
    num_layers: 1
    hidden_size: 256
    max_length: 25
  beam_search:
    beam_size: 16
    penalty: 0
  attention:
    type: bahdanau
    size: 256
  dropout: 0.1
  teacher_forcing_ratio: 1.0
  decoding_method: greedy
dataset:
  name: src.datasets.wmt.builder.WMT14
  source: de
  target: en
  output_format: text
  debug_size: 20
  unit: word
  special_tokens: [sos, eos, oov, pad]
  sort: true
train:
  batch_size: 32
  num_epochs: 100
  optimizer:
    name: sgd
    lr: 1.
  lr_scheduler:
    milestones: [10, 20, 30]
    gamma: 0.1
  max_grad_norm: 1.0
test:
  batch_size: 16
  metrics: [bleu]