backend: pytorch
env:
  main:
    title: Results on image datasets
    variables:
      dataset:
        - dlex.datasets.image.MNIST
        - dlex.datasets.image.CIFAR10
model:
  name: src.models.cnn.SimpleModel
dataset:
  name: ~dataset
train:
  eval: [dev, test]
  batch_size: 256
  num_epochs: 30
  optimizer:
    name: adam
    lr: 0.001
  max_grad_norm: 1.0
test:
  metrics: [err]
