backend: pytorch
env:
  default:
    title: Results on image datasets
    variables:
      dataset:
        - dlex.datasets.image.MNIST
        - dlex.datasets.image.CIFAR10
      num_channels:
        - 20, 50
        - 10, 20
model:
  name: src.models.simple_cnn.SimpleCNN
  kernel_size: 3
  num_channels: ~num_channels
dataset:
  name: ~dataset
train:
  eval: [dev, test]
  batch_size: 1024
  num_epochs: 30
  optimizer:
    name: adam
    lr: 0.001
  max_grad_norm: 1.0
  log_every: 0.1e
test:
  metrics: [err]
