backend: tensorflow
env:
  default:
    title: Results on image datasets
    variables:
      dataset:
        - src.datasets.mnist.MNIST
      num_channels:
        - 20, 50
model:
  name: src.models.tf.dnn.DNN
  kernel_size: 3
  num_channels: ~num_channels
dataset:
  name: ~dataset
train:
  eval: [dev, test]
  batch_size: 1024
  num_epochs: 30
  optimizer:
    name: adam
    lr: 0.001
  max_grad_norm: 1.0
  log_every: 0.1e
test:
  metrics: [err]
