model:
  name: dlex.torch.models.attention.NMT
  encoder:
    rnn_type: lstm
    bidirectional: false
    num_layers: 2
    input_size: 256
    hidden_size: 256
    output_size: 256
    embedding: none
    update_embedding: true
  decoder:
    rnn_type: lstm
    use_attention: true
    num_layers: 1
    hidden_size: 256
    max_length: 50
  attention:
    type: bahdanau
    size: 256
  beam_search:
    beam_size: 16
    penalty: 0
  dropout: 0.1
  teacher_forcing_ratio: 1.0
  decoding_method: beam_search
dataset:
  name: src.datasets.iwslt.builder.IWSLT15
  source: en
  target: vi
  output_format: text
  unit: word
  special_tokens: [sos, eos, oov, pad]
train:
  batch_size: 64
  num_epochs: 100
  optimizer:
    name: adam
    lr: 0.01
  max_grad_norm: 5.0
test:
  batch_size: 16
  metrics:
    - bleu
