backend: pytorch
model:
  name: src.models.qanet.QANet
  connector_dim: 128
  num_heads: 8
  hidden_size: 200
  maxout_pool_size: 16
  max_decoder_steps: 4
  dropout: 0.1
  dropout_char: 0.05
dataset:
  name: src.datasets.squad.SQuAD_V1
  paragraph_max_length: 400
  question_max_length: 50
  answer_max_len: 30
  char_dim: 200
  embeddings:
    pretrained: GloVe
    name: 840B
    dim: 300
    freeze: true
train:
  num_epochs: 100
  batch_size: 16
  eval: [dev]
  optimizer:
    name: adam
    lr: 0.001
test:
  batch_size: 16
  metrics: [acc]