model:
  name: src.models.rnn.RNNLM
  dropout: 0.5
  rnn_type: lstm
  num_layers: 2
  hidden_size: 1500
dataset:
  name: src.datasets.common_voice.CommonVoiceLM
  unit: word
  output_format: text
  bptt_len: 10
  embedding_dim: 300
train:
  batch_size: 256
  num_epochs: 100
  optimizer:
    name: adam
    lr: 0.001
  max_grad_norm: 0.25
  save_every: 3600s
  log_every: 3600s
test:
  batch_size: 256
  metrics: [acc]
