#!/usr/bin/env bash
#export "HCOPY_PATH=r"C:\Programs\htk\bin.win32\HCopy.exe""
#echo "export HCOPY_PATH=./bin" > ~/.bashrc
echo "Please get a username and password from HTK website http://htk.eng.cam.ac.uk/download.shtml"
read -p "Username: " username
read -p "Password: " password
wget --user ${username} --password ${password} http://htk.eng.cam.ac.uk/ftp/software/HTK-3.4.1.tar.gz
tar xzf HTK-3.4.1.tar.gz
rm HTK-3.5.beta-2.tar.gz
cd htk
./configure --prefix=/tmp --disable-hslab
make all
