model:
  name: dlex.torch.models.attention.NMT
  encoder:
    rnn_type: lstm
    bidirectional: false
    num_layers: 2
    input_size: 256
    hidden_size: 256
    output_size: 256
  decoder:
    rnn_type: lstm
    use_attention: true
    num_layers: 1
    hidden_size: 256
    max_length: 50
  attention:
    type: bahdanau
    size: 256
  beam_search:
    beam_size: 16
    penalty: 0
  dropout: 0.1
  teacher_forcing_ratio: 1.0
  decoding_method: greedy
dataset:
  name: src.datasets.nlp.conll.builder.CoNLL2014
  output_format: text
  unit: word
  sort: true
  special_tokens: [sos, eos, pad, oov]
train:
  batch_size:
    0: 32
    25: 16
    75: 8
  num_epochs: 100
  optimizer:
    name: sgd
    lr: 0.01
test:
  batch_size: 16
  metrics: [wer]