model:
  name: rnn_crf.Model
  embed_size: 300
  rnn_type: 'lstm'
  bidirectional: true
  hidden_size: 1000
  dropout: 0.5
  num_layers: 2
dataset:
  name: vnpos.Dataset
  embed_unit: 'word'
  tag_type: seg
loss: output_mean
batch_size: 8
test_batch_size: 16
num_epochs: 30
optimizer:
  name: adam
  lr: 0.01
metrics:
  - ser
output_format: word+tag
