model: rnn_crf.Model
dataset:
  name: vnpos.Dataset
  tag_type: pos
loss: output_mean
batch_size: 128
test_batch_size: 16
num_epochs: 30
optimizer:
  name: adam
  lr: 0.01
metrics:
  - ser
embed_unit: 'word'
embed_size: 300
rnn_type: 'lstm'
bidirectional: true
hidden_size: 1000
dropout: 0.5
num_layers: 2
