model: rnn_crf
dataset:
  name: vnpos
  tag_type: pos
batch_size: 128
test_batch_size: 16
num_epochs: 30
optimizer:
  name: adam
  lr: 0.01
metrics:
  - ser
embed_unit: 'word'
embed_size: 300
rnn_type: 'bilstm'
hidden_size: 1000
dropout: 0.5
num_layers: 2
