model:
  name: src.models.wavenet.WaveNet
  input_size: 256
  residual_channels: 32
  bias: false
  num_blocks: 4
  kernel_size: 2
  num_layers: 10
dataset:
  name: src.datasets.nsdtsea.NSDTSEA
batch_size: 128
num_epochs: 50
optimizer:
  name: adam
  lr: 0.1
max_length: 10
teacher_forcing_ratio: 0.0
metrics:
  - bleu
