backend: pytorch
model:
  name: dlex.torch.models.attention.Attention
  alias: attention
  encoder:
    rnn_type: lstm
    bidirectional: false
    num_layers: 5
    input_size: 256
    hidden_size: 512
    output_size: 256
  decoder:
    rnn_type: lstm
    use_attention: true
    num_layers: 1
    hidden_size: 256
    output_size: 256
    max_length: 20
  beam_search:
    beam_size: 16
    penalty: 0.5
  attention:
    type: bahdanau
    size: 256
  decoding_method: greedy
  dropout: 0.2
  teacher_forcing_ratio: 0.5
dataset:
  name: dlex.datasets.voice.librispeech.builder.LibriSpeech
  alias: librispeech
  unit: word
  output_format: "text"
  debug_size: 100
  sort: true
  feature:
    tool: python_speech_features
  vocab:
    sos_eos: true
    blank: false
batch_size: 8
num_epochs: 300
optimizer:
  name: adam
  lr: 0.001
max_grad_norm: 5.0
metrics:
  - wer
