model:
  name: dlex.torch.models.attention.Attention
  encoder:
    rnn_type: lstm
    bidirectional: false
    num_layers: 3
    input_size: 256
    hidden_size: 256
    output_size: 256
  decoder:
    rnn_type: lstm
    use_attention: true
    num_layers: 1
    hidden_size: 256
    output_size: 256
    max_length: 100
  beam_search:
    beam_size: 16
    penalty:
  attention:
    type: bahdanau
    size: 128
  decoding_method: greedy
  dropout: 0.0
  teacher_forcing_ratio: 0.5
dataset:
  alias: vivos
  unit: char
  output_format: text
  debug_size: 100
  sort: true
  special_tokens: [sos, eos, oov, pad]
  feature:
    tool: python_speech_features
    file_type: npy
    num_filters: 40
train:
  batch_size: 8
  num_epochs: 1000
  optimizer:
    name: sgd
    lr: 0.01
  max_grad_norm: 5.
  save_every: 1e
  log_every: 0.1e
test:
  batch_size: 4
  metrics: [wer]