backend: pytorch
model:
  name: dlex.torch.models.ctc.CTC
  hidden_size: 512
  num_layers: 5
  bidirectional: false
  dropout: 0
dataset:
  name: dlex.datasets.voice.common_voice.common_voice.CommonVoiceBuilder
  alias: common_voice
  unit: char
  max_target_length: 250
  max_source_length: 2000
  output_format: "text"
  debug_size: 100
  feature:
    tool: htk
    file_type: htk
    num_filters: 120
  special_tokens: [sos, eos, oov, pad]
train:
  batch_size: 16
  num_epochs: 300
  optimizer:
    name: sgd
    lr: 0.01
  max_grad_norm: 1.0
  save_every: 0.05e
  log_every: 60s
test:
  batch_size: 4
  metrics: [wer]
