backend: pytorch
model:
  name: dlex.torch.models.ctc.CTC
  hidden_size: 1024
  num_layers: 5
  bidirectional: true
  dropout: 0
dataset:
  name: dlex.datasets.voice.librispeech.builder.LibriSpeech
  alias: common_voice
  unit: char
  max_target_length: 300
  max_source_length: 1500
  output_format: "text"
  debug_size: 100
  feature:
    tool: python_speech_features
    file_type: npy
    num_filters: 120
  special_tokens: [oov, pad]
  sort: true
train:
  batch_size:
    0: 16
    50: 20
  num_epochs: 300
  optimizer:
    name: adam
    lr: 0.001
  max_grad_norm: 1.0
  save_every: 1800s
  log_every: 60s
test:
  batch_size: 4
  metrics: [wer]
