backend: pytorch
model:
  name: dlex.torch.models.ctc.CTC
  hidden_size: 512
  num_layers: 5
  bidirectional: false
  dropout: 0
dataset:
  name: src.datasets.common_voice.common_voice.CommonVoice
  alias: common_voice
  unit: char
  max_target_length: 100
  max_source_length: 1200
  output_format: "text"
  debug_size: 100
  feature:
    tool: python_speech_features
    file_type: npy
    num_filters: 120
  special_tokens: [oov, pad]
  sort: true
train:
  batch_size:
    0: 50
    50: 30
  num_epochs: 300
  optimizer:
    name: adadelta
    lr: 0.001
  max_grad_norm: 1.0
  save_every: 0.05e
  log_every: 60s
test:
  batch_size: 4
  metrics: [wer]
