model:
  name: dlex.torch.models.ctc.CTC
  hidden_size: 256
  num_layers: 3
  bidirectional: false
  dropout: 0
dataset:
  alias: vivos
  unit: char
  special_tokens: [blank]
  output_format: text
  feature:
    tool: python_speech_features
    num_filters: 40
  sort: true
train:
  batch_size: 64
  num_epochs: 1000
  max_grad_norm: 1.0
  optimizer:
    name: sgd
    lr: 0.1
test:
  metrics:
    - wer
