model:
  name: dlex.torch.models.ctc.CTC
  input_size: 120
  hidden_size: 512
  num_layers: 3
  max_gradient_norm: 5.0
  bidirectional: false
  dropout_p: 0.0
dataset:
  name: src.datasets.vivos.VIVOS
  unit: char
  vocab:
    sos_eos: false
    blank: true
  output_format: text
batch_size: 20
num_epochs: 100
max_grad_norm: 5.0
optimizer:
  name: adam
  lr: 0.001
metrics:
  - wer
