model:
  name: dlex.torch.models.ctc.CTC
  input_size: 32
  hidden_size: 64
  num_layers: 2
  bidirectional: false
  dropout: 0.0
dataset:
  name: dlex.datasets.dummy.Dummy
  vocab:
    sos_eos: false
    blank: true
  output_format: null
batch_size: 16
num_epochs: 100
max_grad_norm: 5.0
optimizer:
  name: adam
  lr: 0.01
metrics:
  - wer